import 'package:flutter/material.dart';
import 'storage.dart';
class ReportsPage extends StatelessWidget{
 const ReportsPage({super.key});
 Future<Map<String,num>> data()async{final p=await LocalStore.patients(),a=await LocalStore.appointments(),g=await LocalStore.packages(),i=await LocalStore.invoices();return {'patients':p.length,'appointments':a.length,'packages':g.length,'sessions':g.fold<num>(0,(s,x)=>s+x.sessions-x.remaining),'revenue':i.fold<num>(0,(s,x)=>s+x.paid),'outstanding':i.fold<num>(0,(s,x)=>s+x.remaining)};}
 @override Widget build(BuildContext c)=>FutureBuilder<Map<String,num>>(future:data(),builder:(c,s){final d=s.data??{};return ListView(padding:const EdgeInsets.all(16),children:[const Text('التقارير',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:14),_R('إجمالي المرضى',(d['patients']??0).toString(),Icons.people),_R('إجمالي المواعيد',(d['appointments']??0).toString(),Icons.event),_R('الباقات',(d['packages']??0).toString(),Icons.inventory_2),_R('الجلسات المنفذة',(d['sessions']??0).toString(),Icons.medical_services),_R('إجمالي المدفوع',(d['revenue']??0).toStringAsFixed(0),Icons.payments),_R('إجمالي المتبقي',(d['outstanding']??0).toStringAsFixed(0),Icons.account_balance_wallet)]);});
}
class _R extends StatelessWidget{final String t,v;final IconData i;const _R(this.t,this.v,this.i);@override Widget build(BuildContext c)=>Card(child:ListTile(leading:Icon(i,color:Theme.of(c).colorScheme.primary),title:Text(t),trailing:Text(v,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))));}
class SettingsPage extends StatefulWidget{const SettingsPage({super.key});@override State<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{final name=TextEditingController(),phone=TextEditingController(),address=TextEditingController();bool whatsapp=false,sms=false;
 @override void initState(){super.initState();_load();}
 Future<void> _load()async{final s=await LocalStore.settings();name.text=s['name']??'نظام وسيم الطبي PRO';phone.text=s['phone']??'';address.text=s['address']??'';if(mounted)setState((){whatsapp=s['whatsapp']=='true';sms=s['sms']=='true';});}
 Future<void> _save()async{await LocalStore.saveSettings({'name':name.text.trim(),'phone':phone.text.trim(),'address':address.text.trim(),'whatsapp':'$whatsapp','sms':'$sms'});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم حفظ إعدادات المركز')));}
 @override Widget build(BuildContext c)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(appBar:AppBar(title:const Text('إعدادات المركز')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:name,decoration:const InputDecoration(labelText:'اسم المركز',prefixIcon:Icon(Icons.business))),const SizedBox(height:12),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'رقم التواصل',prefixIcon:Icon(Icons.phone))),const SizedBox(height:12),TextField(controller:address,decoration:const InputDecoration(labelText:'العنوان',prefixIcon:Icon(Icons.location_on))),const SizedBox(height:8),SwitchListTile(title:const Text('تفعيل قناة WhatsApp'),value:whatsapp,onChanged:(v)=>setState(()=>whatsapp=v)),SwitchListTile(title:const Text('تفعيل قناة SMS'),value:sms,onChanged:(v)=>setState(()=>sms=v)),const SizedBox(height:12),FilledButton.icon(onPressed:_save,icon:const Icon(Icons.save),label:const Text('حفظ الإعدادات')),const SizedBox(height:20),const Card(child:Padding(padding:EdgeInsets.all(14),child:Text('تفعيل القناة يجهز النظام للتكامل، أما الإرسال الآلي الحقيقي فيحتاج بيانات مزود WhatsApp Business أو SMS Gateway.')))])));
}}
